### ISSUE TITLE
问题请教

### ISSUE THREAD

**Issue by 805ya** [WangXFng/MDSTN#1]
请问一下手上还有这两个数据集吗，我跟着连接去下载了没找到，若能分享，将不尽感激

**Comment by WangXFng** [comment]
抱歉哈，这个看起来是23年的工作，其实是19年的工作了（使用的是CNN相关的技术）。建议跟进一些GNN和LLM来解决序列问题哈。数据有百G大小我也没有备份了。我现在做推荐系统相关的，可以看我其他工作，这些数据集都比较小。

**Comment by 805ya** [comment]
好的谢谢




*serendipity
***@***.***

山东科技大学
学生


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WangXFng/MDSTN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月11日(星期五) 下午3:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [WangXFng/MDSTN] 问题请教 (Issue #1)





 
抱歉哈，这个看起来是23年的工作，其实是19年的工作了（使用的是CNN相关的技术）。建议跟进一些GNN和LLM来解决序列问题哈。数据有百G大小我也没有备份了。我现在做推荐系统相关的，可以看我其他工作，这些数据集都比较小。
